/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <div className="flex flex-wrap gap-8 justify-center items-center leading-none bg-blue-600 max-md:px-5  py-2 md:py-4 px-6 md:px-16 lg:px-32 w-full overflow-hidden">
      <div className="flex flex-wrap grow shrink gap-8 items-center self-stretch my-auto min-w-[240px] w-[892px] max-md:max-w-full">
        <div className="flex gap-1.5 items-center self-stretch my-auto text-2xl font-black text-white whitespace-nowrap">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/93a6524f9a3a9bc471579ae7d6dde6f47f24d4e7dac94261c9daa6ac62c929e6?placeholderIfAbsent=true&apiKey=9d6cee3ec6664143a398762bb3c0315c"
            className="object-contain shrink-0 self-stretch my-auto aspect-square w-[50px]"
          />
          <div className="self-stretch my-auto">AeroVision</div>
        </div>
        <div className="self-stretch my-auto text-base text-blue-400 w-[406px]">
          © Copyright 2023. All Rights Reserved.
        </div>
      </div>
      <div className="flex grow shrink gap-2 justify-center items-center self-stretch my-auto text-lg font-semibold text-blue-400 min-w-[240px] w-[238px]">
        <div className="self-stretch my-auto rounded-none w-[132px]">
          FOLLOW US:
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/152b84f7740e24b48e8f8ab1edfe8dd818b38a2007796070fc63101b7150d7ae?placeholderIfAbsent=true&apiKey=9d6cee3ec6664143a398762bb3c0315c"
          className="object-contain shrink-0 self-stretch my-auto aspect-square w-[30px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/75826b789c8e01eb3ca71649880a6f020510d04bc5c8361fa43c82ab51c2e65e?placeholderIfAbsent=true&apiKey=9d6cee3ec6664143a398762bb3c0315c"
          className="object-contain shrink-0 self-stretch my-auto aspect-square w-[30px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/46da435585316292a1ae818c296a1fbdf6aa02b6068a934eec3c2eb703ac7ad2?placeholderIfAbsent=true&apiKey=9d6cee3ec6664143a398762bb3c0315c"
          className="object-contain shrink-0 self-stretch my-auto aspect-square w-[30px]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/cb56b780b2af1733563ddf0a8a5e1ae11d7d01cfd084e95b8bee5a6ac89506c9?placeholderIfAbsent=true&apiKey=9d6cee3ec6664143a398762bb3c0315c"
          className="object-contain shrink-0 self-stretch my-auto aspect-square w-[30px]"
        />
      </div>
    </div>
  );
};

export default Footer;
