/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col  bg-white">
      <Header
        logo="https://cdn.builder.io/api/v1/image/assets/TEMP/671edbfe0268a0611b3c2700f2bda78df25508a1432826a3d8b1411180f2eb53?placeholderIfAbsent=true&apiKey=9d6cee3ec6664143a398762bb3c0315c"
        menuItems={["Home", "About Me", "Services", "Blog", "Contact Me"]}
      />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
