/**
 * This code was generated by Builder.io.
 */
import React from "react";

type PortfolioProps = {
  categories: string[];
  projects: string[];
};

const Portfolio: React.FC<PortfolioProps> = ({ categories, projects }) => {
  return (
    <section className="flex z-10 flex-col items-center mt-0 bg-white max-md:px-5 max-md:mt-0 max-md:max-w-full  py-2 md:py-4 px-6 md:px-16 lg:px-32 w-full overflow-hidden">
      <div className="flex flex-col px-4 max-w-full rounded-none w-[684px]">
        <h2 className="self-center ml-3 text-xl font-semibold text-blue-600 uppercase tracking-[2px]">
          Our projects
        </h2>
        <p className="mt-6 text-5xl font-bold text-center leading-[50px] text-neutral-800 max-md:max-w-full max-md:text-4xl max-md:leading-10">
          Presenting My Design Portfolio and Case Studies
        </p>
      </div>
      <div className="flex flex-wrap gap-6 justify-center items-center mt-12 text-xl font-semibold text-blue-600 max-md:mt-10 max-md:max-w-full">
        {categories.map((category, index) => (
          <button
            key={index}
            className={`gap-2.5 self-stretch px-8 py-3.5 my-auto ${
              index === 0
                ? "text-white bg-blue-600"
                : "bg-white border border-blue-600"
            } min-h-[50px] rounded-[50px] max-md:px-5`}
          >
            {category}
          </button>
        ))}
      </div>
      <div className="flex flex-wrap gap-8 items-center mt-12 max-w-full w-[1278px] max-md:mt-10">
        {projects.map((project, index) => (
          <div
            key={index}
            className="flex flex-col grow shrink self-stretch my-auto bg-white rounded-2xl border border-solid border-zinc-300 min-w-[240px] w-[325px]"
          >
            <img
              loading="lazy"
              src={project}
              alt={`Project ${index + 1}`}
              className="object-contain max-w-full rounded-2xl aspect-[1.11] w-[406px]"
            />
          </div>
        ))}
      </div>
    </section>
  );
};

export default Portfolio;
